--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

--
-- Data for Name: regioni; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO regioni VALUES ('Lazio                                                                                               ', 'Roma                                                                                                ', 'http://www.regione.lazio.it/                                                                        ', 'Lazio.gif                                                                                           ', '12');
INSERT INTO regioni VALUES ('Emilia-Romagna                                                                                      ', 'Bologna                                                                                             ', 'http://www.regione.emilia-romagna.it/                                                               ', 'Emilia-Romagna.gif                                                                                  ', '08');
INSERT INTO regioni VALUES ('Abruzzo                                                                                             ', 'L''Aquila                                                                                            ', 'http://www.regione.abruzzo.it/                                                                      ', 'Abruzzo.gif                                                                                         ', '13');
INSERT INTO regioni VALUES ('Calabria                                                                                            ', 'Catanzaro                                                                                           ', 'http://www.regione.calabria.it/                                                                     ', 'Calabria.gif                                                                                        ', '18');
INSERT INTO regioni VALUES ('Campania                                                                                            ', 'Napoli                                                                                              ', 'http://www.regione.campania.it/                                                                     ', 'Campania.gif                                                                                        ', '15');
INSERT INTO regioni VALUES ('Liguria                                                                                             ', 'Genova                                                                                              ', 'http://www.regione.liguria.it/                                                                      ', 'Liguria.gif                                                                                         ', '07');
INSERT INTO regioni VALUES ('Molise                                                                                              ', 'Campobasso                                                                                          ', 'http://www.regione.molise.it/                                                                       ', 'Molise.gif                                                                                          ', '14');
INSERT INTO regioni VALUES ('Puglia                                                                                              ', 'Bari                                                                                                ', 'http://www.regione.puglia.it/                                                                       ', 'Puglia.gif                                                                                          ', '16');
INSERT INTO regioni VALUES ('Valle d''Aosta                                                                                       ', 'Aosta                                                                                               ', 'http://www.regione.vda.it/                                                                          ', 'Valle-d''Aosta.gif                                                                                   ', '02');
INSERT INTO regioni VALUES ('Sardegna                                                                                            ', 'Cagliari                                                                                            ', 'http://www.regione.sardegna.it/                                                                     ', 'Sardegna.gif                                                                                        ', '20');
INSERT INTO regioni VALUES ('Umbria                                                                                              ', 'Perugia                                                                                             ', 'http://www.regione.umbria.it/                                                                       ', 'Umbria.gif                                                                                          ', '10');
INSERT INTO regioni VALUES ('Basilicata                                                                                          ', 'Potenza                                                                                             ', 'http://www.basilicatanet.it/                                                                        ', 'Basilicata.gif                                                                                      ', '17');
INSERT INTO regioni VALUES ('Piemonte                                                                                            ', 'Torino                                                                                              ', 'http://www.regione.piemonte.it/                                                                     ', 'Piemonte.gif                                                                                        ', '01');
INSERT INTO regioni VALUES ('Marche                                                                                              ', 'Ancona                                                                                              ', 'http://www.regione.marche.it/                                                                       ', 'Marche.gif                                                                                          ', '11');
INSERT INTO regioni VALUES ('Toscana                                                                                             ', 'Firenze                                                                                             ', 'http://www.regione.toscana.it/                                                                      ', 'Toscana.gif                                                                                         ', '09');
INSERT INTO regioni VALUES ('Veneto                                                                                              ', 'Venezia                                                                                             ', 'http://www.regione.veneto.it/                                                                       ', 'Veneto.gif                                                                                          ', '05');
INSERT INTO regioni VALUES ('Trentino-Alto Adige                                                                                 ', 'Trento                                                                                              ', 'http://www.regione.taa.it/                                                                          ', 'Trentino-Alto-Adige.gif                                                                             ', '04');
INSERT INTO regioni VALUES ('Friuli-Venezia Giulia                                                                               ', 'Trieste                                                                                             ', 'http://www.regione.fvg.it/                                                                          ', 'Friuli-Venezia-Giulia.gif                                                                           ', '06');
INSERT INTO regioni VALUES ('Lombardia                                                                                           ', 'Milano                                                                                              ', 'http://www.regione.lombardia.it/                                                                    ', 'Lombardia.gif                                                                                       ', '03');
INSERT INTO regioni VALUES ('Sicilia                                                                                             ', 'Palermo                                                                                             ', 'http://www.regione.sicilia.it/                                                                      ', 'Sicilia.gif                                                                                         ', '19');


--
-- PostgreSQL database dump complete
--

